module.exports = {
  "react/boolean-prop-naming": 0,
  "react/button-has-type": 0,
  "react/default-props-match-prop-types": [2, { "allowRequiredDefaults": false }],
  "react/destructuring-assignment": 0,
  "react/display-name": 0,
  "react/forbid-component-props": 0,
  "react/forbid-dom-props": 0,
  "react/forbid-elements": 0,
  "react/forbid-prop-types": [2, { "forbid": ['any'] }],
  "react/forbid-foreign-prop-types": 0,
  "react/no-access-state-in-setstate": 2,
  "react/no-array-index-key": 0,
  "react/no-children-prop": 2,
  "react/no-danger": 0,
  "react/no-danger-with-children": 2,
  "react/no-deprecated": 2,
  "react/no-did-mount-set-state": 0,
  "react/no-did-update-set-state": 0,
  "react/no-direct-mutation-state": 2,
  "react/no-find-dom-node": 2,
  "react/no-is-mounted": 2,
  "react/no-multi-comp": 2,
  "react/no-redundant-should-component-update": 2,
  "react/no-render-return-value": 2,
  "react/no-set-state": 0,
  "react/no-typos": 2,
  "react/no-string-refs": [2, { "noTemplateLiterals": true }],
  "react/no-this-in-sfc": 2,
  "react/no-unescaped-entities": 0,
  "react/no-unknown-property": 2,
  "react/no-unsafe": [2, { "checkAliases": true }],
  "react/no-unused-prop-types": 0,
  "react/no-unused-state": 2,
  "react/no-will-update-set-state": 2,
  "react/prefer-es6-class": 0,
  "react/prefer-read-only-props": 0,
  "react/prefer-stateless-function": 0,
  "react/prop-types": 2,
  "react/react-in-jsx-scope": 2,
  "react/require-default-props": 0,
  "react/require-optimization": [2, { allowDecorators: ['pureRender'] }],
  "react/require-render-return": 2,
  "react/self-closing-comp": 2,
  "react/sort-comp": 0,
  "react/sort-prop-types": 0,
  "react/state-in-constructor": 0,
  "react/static-property-placement": 0,
  "react/style-prop-object": 2,
  "react/void-dom-elements-no-children": 2,
  "react/jsx-boolean-value": 0,
  "react/jsx-child-element-spacing": 0,
  "react/jsx-closing-bracket-location": [2, "line-aligned"],
  "react/jsx-closing-tag-location": 2,
  "react/jsx-curly-newline": [2, { multiline: "consistent", singleline: "consistent" }],
  "react/jsx-curly-spacing": [2, { "when": "never", "children": { "when": "always" } }],
  "react/jsx-equals-spacing": [2, "never"],
  "react/jsx-filename-extension": [2, { "extensions": [".jsx", ".tsx"] }],
  "react/jsx-first-prop-new-line": [2, "multiline"],
  "react/jsx-handler-names": 0,
  "react/jsx-indent": [2, 2, { checkAttributes: true, indentLogicalExpressions: true }],
  "react/jsx-indent-props": [2, 2],
  "react/jsx-key": 2,
  "react/jsx-max-depth": 0,
  "react/jsx-max-props-per-line": [2, { "maximum": 1, "when": "multiline" }],
  "react/jsx-no-bind": [2, { allowArrowFunctions: true }],
  "react/jsx-no-comment-textnodes": 2,
  "react/jsx-no-duplicate-props": 2,
  "react/jsx-no-literals": 0,
  "react/jsx-no-target-blank": 0,
  "react/jsx-no-undef": [2, { allowGlobals: true }],
  "react/jsx-one-expression-per-line": [2, { allow: "single-child" }],
  "react/jsx-curly-brace-presence": [2, { props: "never", children: "never" }],
  "react/jsx-fragments": 2,
  "react/jsx-pascal-case": 2,
  "react/jsx-props-no-multi-spaces": 2,
  "react/jsx-props-no-spreading": 0,
  "react/jsx-sort-default-props": 0,
  "react/jsx-sort-props": 0,
  "react/jsx-tag-spacing": [2, { closingSlash: "never", beforeSelfClosing: "always", afterOpening: "never", beforeClosing: "never" }],
  "react/jsx-uses-react": 2,
  "react/jsx-uses-vars": 2,
  "react/jsx-wrap-multilines": [2, {
    "declaration": "parens-new-line",
    "assignment": "parens",
    "return": "parens-new-line",
    "arrow": "parens-new-line",
    "condition": "parens-new-line",
    "logical": "parens-new-line",
    "prop": "parens-new-line"
  }]
}
